apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca.crt
          name: ca-bundle-cert
          subPath: ca.crt
      volumes:
      - name: ca-bundle-cert
        secret:
          secretName: argocd-tls
          items:
          - key: ca.crt
            path: ca.crt