expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
      notarySecretName: notary-tls
  ingress:
    hosts:
      core: harbor.k8s.chimera
      notary: notary.harbor.k8s.chimera
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: private-ica
    notary:
      annotations:
        cert-manager.io/common-name: harbor-notary-tls
    harbor:
      annotation:
        cert-manager.io/common-name: harbor-core-tls

externalURL: https://harbor.k8s.chimera

internalTLS:
  enabled: false

ipFamily:
  ipv6:
    enabled: false

persistence:
  enabled: true

logLevel: info

caSecretName: ""
caBundleSecretName: ca-bundle
harborAdminPassword: "eyGBd7gt"
secretKey: "6JVciYnjwEFoSdAR"

metrics:
  enabled: true

trace:
  enabled: false