apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
