apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-deployment
  source:
    repoURL: "{{ .Values.controlRepo }}"
    targetRevision: "{{ .Values.targetRevision }}"
    path: applications/heimdall
    helm:
      values: |
        domain: {{ .Values.domain }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.projectNamespace }}

  syncPolicy:
    retry:
      limit: 1
      backoff:
        duration: 5m
        factor: 2
        maxDuration: 30m
    syncOptions:
    - CreateNamespace=true
