apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-deployment
  source:
    repoURL: "{{ .Values.controlRepo }}"
    targetRevision: "{{ .Values.targetRevision }}"
    path: applications/longhorn

    helm:
      valueFiles:
      - values.yaml
      values: |
{{ toYaml .Values.longhorn | indent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    retry:
      limit: 1
      backoff:
        duration: 5m
        factor: 2
        maxDuration: 30m
    syncOptions:
    - CreateNamespace=true
