---
apiVersion: v1
kind: Secret
metadata:
  name: ca-bundle
  namespace: {{ .Values.projectNamespace }}
stringData:
  ca.crt: |-
{{ indent 4 .Values.certificateAuthority.caBundle }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-bundle
  namespace: prometheus
stringData:
  ca.crt: |-
{{ indent 4 .Values.certificateAuthority.caBundle }}