{{- if .Values.aws -}}
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-credentials
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
{{- end -}}