{{- if .Values.rbac.createRole -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-chimera
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: coredns
{{- end -}}