apiVersion: v1
kind: Service
metadata:
  name: coredns-udp
  namespace: {{ .Release.Namespace  }}
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.externalIP  }}
  selector:
    app: coredns
  ports:
  - name: coredns-dns
    protocol: UDP
    port: 53
    targetPort: 30053
