apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-ca-bundle.yaml

patchesStrategicMerge:
  - patches/secret-argocd.yaml
  - patches/application-master.yaml