apiVersion: v1
kind: Service
metadata:
  name: heimdall-admin-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  selector:
{{ include "app.labels" . | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80